### ISSUE TITLE
iOS 8 compatibility

### ISSUE THREAD

**Issue by manmal** [detroit-labs/IRLSize#11]
Hi! 

Thanks for the great work!
I have a q: Is there a certain reason you upped the deployment target to 10.0? I used the lib previously (I think 0.4.3) and it was compatible with 8.0. Most apps need at least compatibility with 9.0 nowadays..

**Comment by SlaunchaMan** [comment]
Hi! The library requires iOS 10 because version 1.0 uses `NSMeasurement` to measure size. It wouldn’t be too difficult to support older versions, just a matter of properly marking method availability for the bits that require iOS 10 and exposing the private methods that return floats instead of measurements.

**Comment by SlaunchaMan** [comment]
I have a PR up at #12 that back ports to iOS 8; once it passes I’ll merge it and release an update! If you want, look through the `backporting` branch to see if it suits your needs; you can reference it directly in your Podfile while we wait for Travis.

**Comment by SlaunchaMan** [comment]
Fixed in [1.1.0](https://github.com/detroit-labs/IRLSize/releases/tag/1.1.0)!

**Comment by manmal** [comment]
Awesome, thank you! Much appreciated
